
Basic Level:

In [1]:
# 1. Write a Python program to check if a given number is positive or negative.
n=int(input())
if n>=0:
    print("Positive")
else:
    print("Negative")


 -34


Negative


In [2]:
# 2. Create a program that determines if a person is eligible to vote based on their age.
age=int(input())
if age>=18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

 23


Eligible to vote


In [3]:
# 3. Develop a program to find the maximum of two numbers using if-else statements.
a,b=map(int,input().split())
if a>b:
    print("a is greater ")
else:
    print("b is greater")

 34 54


b is greater


In [ ]:
# 4. Write a Python script to classify a given year as a leap year or not.
yr=int(input())
if yr%4==0:
    print("Leap year")
else:
    print("Not a Leap year")


In [4]:
# 5. Create a program that checks whether a character is a vowel or a consonant.
l=input("Enter a character :")
if l in "AaEeIiOoUu":
    print("Vowel")
else:
    print("Consonant")
    

Enter a character : e


Vowel


In [5]:
# 6. Implement a program to determine whether a given number is even or odd.
n=int(input())
if n%2==0:
    print("Even")
else:
    print("Odd")
    

 10


Even


In [6]:
# 7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.
n=int(input())
if n<0:
    print(-n)
else:
    print(n)

 -4


4


In [8]:
# 8. Develop a program that determines the largest of three given numbers using if-else statements.
a,b,c=map(int,input().split(","))
if a>b:
    if a>c:
        print(f"Greatest is {a}")
    else:
        print(f"Greatest is {c}")
else:
    if b>c:
        print(f"Gretest is {b}")
    else:
        print(f"Greatest is {c}")

 34,45,56


Greatest is 56


In [9]:
# 9. Create a program that checks if a given string is a palindrome.
st=input().strip()
if st==st[::-1]:
    print("The given string is palindrome")
else:
    print("The given string is  not a palindrome")

 malayalam


The given string is palindrome


In [ ]:
# 10. Write a Python program to calculate the grade based on a student's score.
n=int(input("Enter ur perccentage :"))
if n>90:
    print("A+")
elif 80<=n<90:
    print("A")
elif 70<=n<80:
    print("B+")
elif 50<=n<60

Intermediate Level:








In [5]:
# 11. Write a program to find the largest among three numbers using nested if-else statements.
a,b,c=map(int,input().split())
if a>b:
    if a>c:
        print("a is Greatest!")
    else:
        print("c is Greatest!")
else:
    if b>c:
        print("b is Greatest!")
    else:
        print("c is Greatest!")
    

 34 45 56


c is Greatest!


In [8]:
# 12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene.
for _ in range(3):
    a,b,c=map(int,input().split())
    if a==b:
        if a==c:
            print("equilateral triangle")
        else:
            print("isosceles triangle")
    else:
        if a==c:
            print("isosceles triangel")
        elif b==c:
            print("isosceles triangle")
        else:
            print("Scalene triangle")

 75 75 30


isosceles triangle


 60 60 60


equilateral triangle


 60 70 50


Scalene triangle


In [11]:
# 13. Develop a program that checks if a year is a leap year and also if it is a century year.
y=int(input("Enter a year :"))
if y%4==0:
    if y%100==0:
        print(f"{y} is a leap year and also a century year")
    else:
        print(f"{y} is only a leap year ")
else:
    print(f"{y} is not a leap year ")


Enter a year : 400


400 is a leap year and also a century year


In [12]:
# 14. Write a Python script to determine if a number is positive, negative, or zero.
for _ in range(3):
    n=int(input("Enter a number :"))
    if n>0:
        print("Positive")
    elif n<0:
        print("Negative")
    elif n==0:
        print("Zero")
    
    

Enter a number : 0


Zero


Enter a number : 2


Positive


Enter a number : -3


Negative


In [3]:
# 15. Create a program to check if a person is a teenager (between 13 and 19 years old).
age=int(input("Enter ur age :"))
if 13<=age<=19:
    print("Teenager")
else:
    print("Not a teenager")

Enter ur age : 23


Not a teenager


In [5]:
# 16. Develop a program that determines the type of angle based on its measure (acute, obtuse, or right).
angle=int(input("Enter the angle <180"))
if angle<90:
    print("Acute angle")
elif 90<angle<180:
    print("Obtuse angle")
elif angle==90:
    print("Right angle")
else:
    print("Enter the correct angle")

Enter the angle <180 90


Right angle


In [10]:
# 17. Write a Python program to calculate the roots of a quadratic equation
import numpy as np
a=float(input("Enter coefficient of a in ax2+bx+c :"))
b=float(input("Enter coefficient of b in ax2+bx+c :"))
c=float(input("Enter coefficient of c in ax2+bx+c :"))

coefs=[a,b,c]
roots=np.roots(coefs)
for i in roots:
    print(f"The root :{root}")

Enter coefficient of a in ax2+bx+c : 2
Enter coefficient of b in ax2+bx+c : 3
Enter coefficient of c in ax2+bx+c : 5


The root :(-0.49999999999999994-0.9746794344808962j)
The root :(-0.49999999999999994-0.9746794344808962j)


In [10]:
# 17. Write a Python program to calculate the roots of a quadratic equation
import numpy as np
a=float(input("Enter coefficient of a in ax2+bx+c :"))
b=float(input("Enter coefficient of b in ax2+bx+c :"))
c=float(input("Enter coefficient of c in ax2+bx+c :"))

coefs=[a,b,c]
roots=np.roots(coefs)
for i in roots:
    print(f"The root :{root}")

Enter coefficient of a in ax2+bx+c : 2
Enter coefficient of b in ax2+bx+c : 3
Enter coefficient of c in ax2+bx+c : 5


The root :(-0.49999999999999994-0.9746794344808962j)
The root :(-0.49999999999999994-0.9746794344808962j)


In [16]:
# 19. Create a program that determines if a year is a leap year and also if it is evenly divisible by 400.
yr=int(input("Enter a year"))
if yr%4==0:
    if yr%400==0:
        print("It is leap year and is evenly divided by 400")
    else:
        print("It is leap year but not divided by 400")
else:
    print("It is not leap year")


Enter a year 344


It is leap year but not divided by 400


In [14]:
# 18. Implement a program to determine the day of the week based on a user-provided number (1 for Monday, 2 for Tuesday, etc.).
n=int(input("Enter a value between 1-7"))
dic={1:"Monday",2:"Tuesday",3:"Wednesday",4:"Thursday",5:"Friday",6:"Saturday",7:"Sunday"}
print(dic[n])

Enter a value between 1-7 7


Sunday


In [19]:
# 20. Develop a program that checks if a given number is prime or not using nested if-else statements.
n=int(input("Enter a number :"))
if n>1:
    for num in range(2,int(n**0.5)+1):
        if n%num==0:
            print(n," is not a prime number")
            break
    else:
        print(n," is a prime number")
else:
    print(n," is not a prime number")

Enter a number : 397


397  is a prime number


Advanced Level:


In [24]:
# 21. Write a Python program to assign grades based on different ranges of scores using elif statements.
def grades(marks):
    if marks>=90:
        print("A+")
    elif 80<=marks<90:
        print("A")
    elif 70<=marks<80:
        print("B")
    elif 60<= marks<70:
        print("C")
    elif 50<=marks<60:
        print("D")
    else:
        print("Fail")
for i in range(1,6):
    marks=float(input(f"Enter marks of sub{i}:"))
    grades(marks)

Enter marks of sub1: 40


Fail


Enter marks of sub2: 99


A+


Enter marks of sub3: 89


A


Enter marks of sub4: 78


B


Enter marks of sub5: 100


A+


In [2]:
# 23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using  elif statements
bmi=float(input("Enter ur BMI>0 :"))
if bmi<18.5:
    print("you are underweight. You should put some weight or stick to a  pole during winds")
elif 18.5<=bmi<25:
    print("you are absolutely good , keep on it")
elif 25<=bmi<30:
    print(" you are overweight go hit gym ")
elif bmi>=30:
    print("You are obese and should cut crap fat in you ")
else:
    print("Enter the correct value")
    

Enter ur BMI>0 : 25


 you are overweight go hit gym 


In [27]:
# 22. Implement a program to determine the type of a triangle based on its angles.
def triangle_type(angle1, angle2, angle3):    
    if angle1 + angle2 + angle3 == 180 and angle1 > 0 and angle2 > 0 and angle3 > 0:
        if angle1 < 90 and angle2 < 90 and angle3 < 90:
            return "Acute Triangle"
        elif angle1 == 90 or angle2 == 90 or angle3 == 90:
            return "Right Triangle"
        else:
            return "Obtuse Triangle"
    else:
        return "Invalid Triangle"

angle1 = float(input("Enter the first angle: "))
angle2 = float(input("Enter the second angle: "))
angle3 = float(input("Enter the third angle: "))
triangle = triangle_type(angle1, angle2, angle3)
print("The triangle with angles {}, {}, and {} is a {}".format(angle1, angle2, angle3, triangle))


Enter the first angle:  34
Enter the second angle:  60
Enter the third angle:  86


The triangle with angles 34.0, 60.0, and 86.0 is a Acute Triangle


In [3]:
# 24. Create a program that determines whether a given number is positive, negative, or zero using elif  statements.
n=float(input("Enter a integer value"))
if n>0:
    print("Positive")
elif n<0:
    print("Negative")
elif n==0:
    print("Zero")
else:
    print("I said enter a integer ")

Enter a integer value 3


Positive


In [15]:
#### 25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif  statements.
c=input("Enter a single character :")
if c.isalpha() and len(c)==0:
    if c.isupper():
        print("Uppercase")
    elif c.islower():
        print("Lowercase")
    elif not (c.isalnum() or c.isspace()):
        print("Special character")
else:
    print("I said to enter a single  character")

Enter a single character : enfker$$$


I said to enter a single  character


In [18]:
# 26. Implement a program to calculate the discounted price based on different purchase amounts using elif statements
def calculate_discounted_price(amount):
    if amount < 100:
        discount = 0
    elif 100 <= amount < 500:
        discount = 0.05  # 5% discount
    elif 500 <= amount < 1000:
        discount = 0.1   # 10% discount
    else:
        discount = 0.15  # 15% discount

    discounted_price = amount - (amount * discount)
    return discounted_price
purchase_amount = float(input("Enter the purchase amount:"))
discounted_price = calculate_discounted_price(purchase_amount)
print(f"The discounted price is {discounted_price}")


Enter the purchase amount: 5000


The discounted price is 4250.0


In [21]:
# 27. Develop a program to calculate the electricity bill based on different consumption slabs using elif statements
unit=float(input("Enter the no of units used :"))
if unit<=100:
    print("The e-bill is free ")
elif 100< unit <=200:
    print(f"The e-bill is :{100*0.5 +(unit-100)*0.75}rs")
elif 200< unit <=500:
    print(f"The e-bill is :{100*0.5+100*0.75+(unit-200)*1.20}rs")
elif unit>500:
    print(f"The e-bill is :{100*0.5+100*0.75+300*1.20+(unit-500)*1.50}rs")
else:
    print("Enter the correct value")
    


Enter the no of units used : 500


The e-bill is :485.0rs


In [22]:
# 28. Create a program to determine the type of quadrilateral based on its angles and sides using elif statements.
def determine_quadrilateral_type(sides, angles):
    if sides.count(sides[0]) == 4 and angles.count(90) == 4:
        return "Square"
    elif sides[0] == sides[2] and sides[1] == sides[3] and angles.count(90) == 4:
        return "Rectangle"
    elif sides[0] == sides[2] and sides[1] == sides[3]:
        return "Parallelogram"
    elif sides.count(sides[0]) == 4:
        return "Rhombus"
    elif (sides[0] == sides[1] and sides[2] == sides[3]) or (sides[0] == sides[3] and sides[1] == sides[2]):
        return "Kite"
    elif sides[0] == sides[1] or sides[1] == sides[2] or sides[2] == sides[3] or sides[3] == sides[0]:
        return "Trapezoid"
    else:
        return "Quadrilateral"
sides = [float(input("Enter side {}: ".format(i + 1))) for i in range(4)]
angles = [float(input("Enter angle {}: ".format(i + 1))) for i in range(4)]
quadrilateral_type = determine_quadrilateral_type(sides, angles)
print("The quadrilateral is a:", quadrilateral_type)


Enter side 1:  34
Enter side 2:  34
Enter side 3:  54
Enter side 4:  54
Enter angle 1:  60
Enter angle 2:  90
Enter angle 3:  90
Enter angle 4:  60


The quadrilateral is a: Kite


In [23]:
# 29. Write a Python script to determine the season based on a user-provided month using elif statements.
season=input("Enter a season :")
if season in ["December","January","February"]:
    print("Winter")
elif season in ["March","April","May"]:
    print("Spring")
elif season in ["June","July","August"]:
    print("Summer")
elif season in ["September","October","November"]:
    print("Autumn")
else:
    print("Enter a correct season")

Enter a season : March


Spring


In [ ]:
# 30. Implement a program to determine the type of a year (leap or common) and month (30 or 31 days) using  elif statements
def is_leap_year(year):
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        return True
    else:
        return False

def days_in_month(month, year):
    if month in [1, 3, 5, 7, 8, 10, 12]:
        return 31
    elif month in [4, 6, 9, 11]:
        return 30
    elif month == 2:
        if is_leap_year(year):
            return 29
        else:
            return 28
    else:
        return -1  # Invalid month

year = int(input("Enter the year: "))
month = int(input("Enter the month (1-12): "))
if is_leap_year(year):
    print(year, "is a leap year.")
else:
    print(year, "is a common year.")
num_days = days_in_month(month, year)
if num_days == -1:
    print("Invalid month entered.")
else:
    print("The month has", num_days, "days.")


Challenge Level:


In [3]:
# 31. Create a program that validates a password based on complexity rules (length, characters, etc.).
def isvalidpassword(passw):
    if 5<len(passw)<=12:
        for num in passw:
            if (num.isupper()) or (num.islower()) or (num.alphanumeric()) or (num.isdigit()):
                return True
            else:
                return False
    else:
        return False

for _ in range(3):
    passw=input("Enter ur password :").strip()
    print(isvalidpassword(passw))


Enter ur password : hari@123


True


Enter ur password : hariharihari@123


False


Enter ur password : hari,123


True


In [2]:
## 32. Develop a program that performs matrix addition and subtraction based on user input.
row,col=map(int,input("Enter a row col for both matrices :").split())
print("Enter input for mat")
mat=[]
for i in range(row):
    cl=[]
    for j in range(col):
        cl.append(int(input(f"Enter a value in [{i}][{j}] :")))
    mat.append(cl)
print("Enter input for mat1")
mat1=[]
for i in range(row):
    cl=[]
    for j in range(col):
        cl.append(int(input(f"Enter a value in [{i}][{j}] :")))
    mat1.append(cl)
print(mat,mat1)
mat2=[]
for i in range(row):
    cl=[]
    for j in range(col):
        cl.append(mat[i][j]+mat1[i][j])
    mat2.append(cl)
print(f"The addition of two matrices :{mat2}")

mat3=[]
for i in range(row):
    cl=[]
    for j in range(col):
        cl.append(mat[i][j]-mat1[i][j])
    mat3.append(cl)
print(f"The subraction of two matrices :{item for sun in mat3 for item in sun}")



Enter a row col for both matrices : 3 3


Enter input for mat


Enter a value in [0][0] : 1
Enter a value in [0][1] : 2
Enter a value in [0][2] : 3
Enter a value in [1][0] : 4
Enter a value in [1][1] : 5
Enter a value in [1][2] : 6
Enter a value in [2][0] : 7
Enter a value in [2][1] : 8
Enter a value in [2][2] : 9


Enter input for mat1


Enter a value in [0][0] : 9
Enter a value in [0][1] : 8
Enter a value in [0][2] : 7
Enter a value in [1][0] : 6
Enter a value in [1][1] : 5
Enter a value in [1][2] : 4
Enter a value in [2][0] : 3
Enter a value in [2][1] : 2
Enter a value in [2][2] : 1


[[1, 2, 3], [4, 5, 6], [7, 8, 9]] [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
The addition of two matrices :[[10, 10, 10], [10, 10, 10], [10, 10, 10]]
The subraction of two matrices :[[-8, -6, -4], [-2, 0, 2], [4, 6, 8]]


In [8]:
# 33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean  algorithm.
n1,n2=map(int,input().split())
n1d=[]
n2d=[]
if n1==n2:
    print(n1)
for i in range(1,n1+1):
    if n1%i==0:
        n1d.append(i)
for j in range(1,n2+1):
    if n2%j==0:
        n2d.append(j)
same=[]
for num in n1d:
    for nu in n2d:
        if num==nu:
            same.append(num)
print(f"The Gcd of {n1} and {n2} is {max(same)}")

 50 100


The Gcd of 50 and 100 is 50


In [20]:
# 34. Build a program that performs matrix multiplication using nested loops and conditional statements.
import numpy as np
a,b=map(int,input("Enter rows and cols :").split("*"))
x,y=map(int,input("Enter rows and cols  :").split("*"))
mat1=[]
mat2=[]
for i in range(2):
    st=list(map(int,input("Enter elements with space").split()))
    if i==0:
        mat1=np.array(st).reshape(a,b)
    else:
        mat2=np.array(st).reshape(x,y)
print(f"The multiplication of {mat1} and {mat2} :{np.dot(mat1,mat2)}")

Enter rows and cols : 3*4
Enter rows and cols  : 4*3
Enter elements with space 1 2 3 4 5 6 7 8 9 1 2 4
Enter elements with space 9 8 7 6 5 4 3 2 1 2 4 3


The multiplication of [[1 2 3 4]
 [5 6 7 8]
 [9 1 2 4]] and [[9 8 7]
 [6 5 4]
 [3 2 1]
 [2 4 3]] :[[ 38  40  30]
 [118 116  90]
 [101  97  81]]


In [54]:
# 35. Create a program that simulates a basic text-based tic-tac-toe game against the computer.
import random

# Function to print the Tic-Tac-Toe board
def print_board(board):
    for row in board:
        print(" | ".join(row))
        print("-" * 5)

# Function to check if a player has won
def check_winner(board, player):
    # Check rows, columns, and diagonals
    for i in range(3):
        if all([board[i][j] == player for j in range(3)]) or \
           all([board[j][i] == player for j in range(3)]):
            return True
    if all([board[i][i] == player for i in range(3)]) or \
       all([board[i][2-i] == player for i in range(3)]):
        return True
    return False

# Function to make a move for the computer
def computer_move(board):
    while True:
        row = random.randint(0, 2)
        col = random.randint(0, 2)
        if board[row][col] == " ":
            board[row][col] = "O"
            break

# Initialize the board
board = [[" " for _ in range(3)] for _ in range(3)]

# Main game loop
while True:
    # Player's move
    print_board(board)
    row = int(input("Enter row (1, 2, 3): ")) - 1
    col = int(input("Enter column (1, 2, 3): ")) - 1
    if board[row][col] == " ":
        board[row][col] = "X"
    else:
        print("That cell is already taken! Try again.")
        continue

    # Check if player wins
    if check_winner(board, "X"):
        print_board(board)
        print("Congratulations! You win!")
        break

    # Computer's move
    computer_move(board)

    # Check if computer wins
    if check_winner(board, "O"):
        print_board(board)
        print("Sorry, you lose. Better luck next time!")
        break

    # Check for a draw
    if all([cell != " " for row in board for cell in row]):
        print_board(board)
        print("It's a draw!")
        break


  |   |  
-----
  |   |  
-----
  |   |  
-----


Enter row (1, 2, 3):  1
Enter column (1, 2, 3):  3


  |   | X
-----
  |   |  
-----
O |   |  
-----


Enter row (1, 2, 3):  1
Enter column (1, 2, 3):  2


  | X | X
-----
O |   |  
-----
O |   |  
-----


Enter row (1, 2, 3):  1
Enter column (1, 2, 3):  1


X | X | X
-----
O |   |  
-----
O |   |  
-----
Congratulations! You win!


In [39]:
 # 36. Write a program that generates Fibonacci numbers up to a specified term using iterative methods.
def fibo(n):
    fib=[]
    f=0
    s=1
    fib.append(f)
    fib.append(s)
    for i in range(n-2):
        t=f+s
        fib.append(t)
        f=s
        s=t
    return fib
n=int(input("Enter a limit :"))
print(fibo(n))


Enter a limit : 20


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]


In [42]:
# 37. Develop a program that calculates the nth term of the Fibonacci sequence using memoization.
n=int(input("Enter fibo series limit :"))
fibo_list=fibo(n)
i=int(input("Enter the position :"))
print(f"The number in {i}th position is {fibo_list[i-1]}")


Enter fibo series limit : 20
Enter the position : 10


The number in 10th position is 34


In [50]:
# 38. Create a program that generates a calendar for a given month and year using conditional statements.

import calendar
def generate_calendar(month, year):
    cal = calendar.monthcalendar(year, month)

    print(calendar.month_name[month], year)
    print("Mo Tu We Th Fr Sa Su")
    for week in cal:
        for day in week:
            print(f"{day:2d}" if day != 0 else "  ", end=" ")
        print()

def main():
    month = int(input("Enter the month (1-12): "))
    year = int(input("Enter the year: "))
    generate_calendar(month, year)

if __name__ == "__main__":
    main()


Enter the month (1-12):  12
Enter the year:  2025


December 2025
Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7 
 8  9 10 11 12 13 14 
15 16 17 18 19 20 21 
22 23 24 25 26 27 28 
29 30 31             


In [53]:
# 39. Build a program that simulates a basic text-based blackjack game against the computer.

import random

# Function to create a deck of cards
def create_deck():
    ranks = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']
    suits = ['Hearts', 'Diamonds', 'Clubs', 'Spades']
    deck = [{'rank': rank, 'suit': suit} for rank in ranks for suit in suits]
    random.shuffle(deck)
    return deck

# Function to calculate the value of a hand
def calculate_hand_value(hand):
    value = 0
    num_aces = 0
    for card in hand:
        if card['rank'] in ['J', 'Q', 'K']:
            value += 10
        elif card['rank'] == 'A':
            value += 11
            num_aces += 1
        else:
            value += int(card['rank'])
    while value > 21 and num_aces:
        value -= 10
        num_aces -= 1
    return value

# Function to display a hand
def display_hand(hand, hide_first_card=False):
    if hide_first_card:
        print("Dealer's hand:")
        print("Hidden card")
        for card in hand[1:]:
            print(f"{card['rank']} of {card['suit']}")
    else:
        print("Hand:")
        for card in hand:
            print(f"{card['rank']} of {card['suit']}")
    print()

# Main function to play the game
def main():
    print("Welcome to Blackjack!")

    # Create a deck of cards
    deck = create_deck()

    # Initialize player's and dealer's hands
    player_hand = [deck.pop(), deck.pop()]
    dealer_hand = [deck.pop(), deck.pop()]

    # Display player's and dealer's initial hands
    display_hand(player_hand)
    display_hand(dealer_hand, hide_first_card=True)

    # Player's turn
    while calculate_hand_value(player_hand) < 21:
        action = input("Do you want to hit or stand? (h/s): ").lower()
        if action == 'h':
            player_hand.append(deck.pop())
            display_hand(player_hand)
        elif action == 's':
            break

    # Check if player busted
    if calculate_hand_value(player_hand) > 21:
        print("Busted! You lose.")
    else:
        # Dealer's turn
        while calculate_hand_value(dealer_hand) < 17:
            dealer_hand.append(deck.pop())

        # Display dealer's hand
        display_hand(dealer_hand)

        # Determine the winner
        player_value = calculate_hand_value(player_hand)
        dealer_value = calculate_hand_value(dealer_hand)
        if dealer_value > 21 or player_value > dealer_value:
            print("Congratulations! You win.")
        elif dealer_value > player_value:
            print("Dealer wins.")
        else:
            print("It's a tie.")

if __name__ == "__main__":
    main()


Welcome to Blackjack!
Hand:
6 of Hearts
3 of Diamonds

Dealer's hand:
Hidden card
A of Spades



Do you want to hit or stand? (h/s):  h


Hand:
6 of Hearts
3 of Diamonds
Q of Hearts



Do you want to hit or stand? (h/s):  h


Hand:
6 of Hearts
3 of Diamonds
Q of Hearts
K of Spades

Busted! You lose.


In [56]:
# 40. Write a program that generates the prime factors of a given number using trial division.
def prime_factors(n):
    factors = []
    divisor = 2
    while n > 1:
        while n % divisor == 0:
            factors.append(divisor)
            n //= divisor
        divisor += 1
    return factors

def main():
        num = int(input("Enter a positive integer: "))
        if num < 1:
            print("Please enter a positive integer.")
            return
        factors = prime_factors(num)
        if len(factors) == 1:
            print(f"{num} is a prime number.")
        else:
            print(f"The prime factors of {num} are:", factors)
            

if __name__ == "__main__":
    main()


Enter a positive integer:  54


The prime factors of 54 are: [2, 3, 3, 3]
